version: '3.8'

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    container_name: celery_worker
    command: celery -A library_project worker --loglevel=info
    environment:
      - DB_NAME=library_db
      - DB_HOST=db
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    container_name: celery_beat
    command: celery -A library_project beat --loglevel=info --pidfile=
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
